name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tox:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
    runs-on: ${{ matrix.os }}
    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@592cf69
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0c28554
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  pip install poetry tox codecov tox-gh-actions
    - name: Run tox environments
      run: tox
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@07127fd
      with:
        file: coverage.xml
        env_vars: OS,PYTHON
